### ISSUE TITLE
recreate project using adobe/helix-service template repo

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/git-resolve-ref#5]
Reimplement based on https://github.com/adobe/helix-service template

**Comment by stefan-guggisberg** [comment]
created https://github.com/adobe/helix-resolve-git-ref

**Comment by stefan-guggisberg** [comment]
see https://github.com/adobe/helix-home/issues/36

**Comment by trieloff** [comment]
I think you can just copy the boilerplate files into this repo instead of deleting and re-creating it.

**Comment by stefan-guggisberg** [comment]
Too late ;) 

I wanted to test the new service template anyway.

**Comment by stefan-guggisberg** [comment]
done: https://github.com/adobe/helix-resolve-git-ref
